### ISSUE TITLE
Wildcard Import

### ISSUE THREAD

**Issue by MoyaFausto** [fabiolaguna/SkillFactory#1]
https://github.com/fabiolaguna/SkillFactory/blob/fc932f50fb1d5f8c78ddcb3245ef6cef2f6e2b27/CollectionPractice/src/ClassList.java#L1

Fijate que te estas trayendo toda la lib de java.util con ese wildcard import (el import con el *). Se puede correjir desde una config del IDE

**Comment by fabiolaguna** [comment]
Resuelto!
