### ISSUE TITLE
Class Cast

### ISSUE THREAD

**Issue by MoyaFausto** [fabiolaguna/SkillFactory#2]
https://github.com/fabiolaguna/SkillFactory/blob/fc932f50fb1d5f8c78ddcb3245ef6cef2f6e2b27/CollectionPractice/src/Main.java#L21

Ojo aca, si tenemos una clase generica debemos asignarle el tipo generico, asi nos ahorramos el casteo y evitamos las ClassCastExceptions

**Comment by MoyaFausto** [comment]
Nos ahorramos esto https://github.com/fabiolaguna/SkillFactory/blob/fc932f50fb1d5f8c78ddcb3245ef6cef2f6e2b27/CollectionPractice/src/Main.java#L50

**Comment by fabiolaguna** [comment]
Dale buenisimo, gracias Fausto
